"""
CLI tool for configuring the Telegram bot environment.
Interactively creates .env file with necessary configuration.
"""

import sys
from pathlib import Path
from typing import Optional


def get_input(prompt: str, default: Optional[str] = None, required: bool = True) -> str:
    """
    Get user input with optional default value.
    
    Args:
        prompt: Prompt to display
        default: Default value
        required: Whether input is required
        
    Returns:
        User input or default value
    """
    if default:
        prompt = f"{prompt} [{default}]"
    
    prompt += ": "
    
    while True:
        value = input(prompt).strip()
        
        if value:
            return value
        elif default:
            return default
        elif not required:
            return ""
        else:
            print("This field is required. Please enter a value.")


def yes_no(prompt: str, default: bool = False) -> bool:
    """
    Get yes/no input from user.
    
    Args:
        prompt: Prompt to display
        default: Default value
        
    Returns:
        True for yes, False for no
    """
    default_str = "Y/n" if default else "y/N"
    response = input(f"{prompt} [{default_str}]: ").strip().lower()
    
    if not response:
        return default
    
    return response in ("y", "yes")


def main() -> None:
    """Main CLI function."""
    print("=" * 60)
    print("Pydantic AI Telegram Bot Configuration")
    print("=" * 60)
    print()
    print("This tool will help you create a .env file with the necessary")
    print("configuration for your Telegram bot.")
    print()
    
    # Bot token
    print("1. Telegram Bot Token")
    print("   Get this from @BotFather on Telegram")
    bot_token = get_input("Enter your bot token", required=True)
    print()
    
    # Chat IDs
    print("2. Allowed Chat IDs (optional)")
    print("   Comma-separated list of chat IDs that can use the bot")
    print("   Leave empty to allow all chats")
    chat_ids = get_input("Enter allowed chat IDs", required=False)
    print()
    
    # Usernames
    print("3. Allowed Usernames (optional)")
    print("   Comma-separated list of usernames that can use the bot")
    print("   Leave empty to allow all users")
    usernames = get_input("Enter allowed usernames", required=False)
    print()
    
    # Transcription service
    print("4. Voice Transcription Service")
    print("   Choose how to transcribe voice messages:")
    print("   1) Local Whisper (requires openai-whisper package)")
    print("   2) OpenAI API (requires openai package and API key)")
    print("   3) None (voice messages won't be supported)")
    
    transcription_choice = get_input("Enter choice (1/2/3)", default="1")
    
    openai_api_key = ""
    transcription_service = "none"
    whisper_model = "turbo"
    
    if transcription_choice == "1":
        transcription_service = "local"
        print()
        print("5. Local Whisper Model")
        print("   Available models: tiny, base, small, medium, large, turbo")
        print("   Larger models are more accurate but slower")
        whisper_model = get_input("Enter model", default="turbo")
    
    elif transcription_choice == "2":
        transcription_service = "openai"
        print()
        print("5. OpenAI API Configuration")
        openai_api_key = get_input("Enter OpenAI API key", required=True)
    
    print()
    
    # OpenAI for the agent
    use_openai_agent = yes_no("6. Use OpenAI for the AI agent?", default=True)
    
    if use_openai_agent and not openai_api_key:
        openai_api_key = get_input("Enter OpenAI API key", required=True)
    
    print()
    
    # Max history
    print("7. Maximum Conversation History")
    max_history = get_input("Enter max messages to keep", default="50")
    print()
    
    # Create .env file
    env_path = Path.cwd() / ".env"
    
    if env_path.exists():
        if not yes_no(f".env file already exists at {env_path}. Overwrite?", default=False):
            print("Configuration cancelled.")
            return
    
    # Write .env file
    env_content = f"""# Telegram Bot Configuration
# Generated by pydantic-ai-telegram-config

# Telegram Bot Token (required)
TELEGRAM_BOT_TOKEN={bot_token}

# Access Control (optional)
# Comma-separated list of allowed chat IDs
TELEGRAM_ALLOWED_CHAT_IDS={chat_ids}

# Comma-separated list of allowed usernames (without @)
TELEGRAM_ALLOWED_USERNAMES={usernames}

# Transcription Service: local, openai, or none
TRANSCRIPTION_SERVICE={transcription_service}

# Local Whisper Model (if using local transcription)
# Options: tiny, base, small, medium, large, turbo
WHISPER_MODEL={whisper_model}

# OpenAI API Key (if using OpenAI transcription or agent)
OPENAI_API_KEY={openai_api_key}

# Maximum conversation history to maintain
MAX_HISTORY_MESSAGES={max_history}
"""
    
    env_path.write_text(env_content)
    
    print("=" * 60)
    print(f"✅ Configuration saved to: {env_path}")
    print("=" * 60)
    print()
    print("Next steps:")
    print("1. Install required dependencies:")
    
    if transcription_service == "local":
        print("   pip install pydantic-ai-telegram[whisper]")
    elif transcription_service == "openai":
        print("   pip install pydantic-ai-telegram[openai]")
    else:
        print("   pip install pydantic-ai-telegram")
    
    print()
    print("2. Create your bot script (see examples/minimal_bot.py)")
    print("3. Run your bot!")
    print()


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nConfiguration cancelled.")
        sys.exit(1)
    except Exception as e:
        print(f"\n\nError: {e}")
        sys.exit(1)

